//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POPSMvcWcfApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/POPSWcfService.Entities")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ITRateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITCode {
            get {
                return this.ITCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ITCodeField, value) != true)) {
                    this.ITCodeField = value;
                    this.RaisePropertyChanged("ITCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITDesc {
            get {
                return this.ITDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ITDescField, value) != true)) {
                    this.ITDescField = value;
                    this.RaisePropertyChanged("ITDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ITRate {
            get {
                return this.ITRateField;
            }
            set {
                if ((this.ITRateField.Equals(value) != true)) {
                    this.ITRateField = value;
                    this.RaisePropertyChanged("ITRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://schemas.datacontract.org/2004/07/POPSWcfService.Entities")]
    [System.SerializableAttribute()]
    public partial class Supplier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUPLADDRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUPLNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUPLNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUPLADDR {
            get {
                return this.SUPLADDRField;
            }
            set {
                if ((object.ReferenceEquals(this.SUPLADDRField, value) != true)) {
                    this.SUPLADDRField = value;
                    this.RaisePropertyChanged("SUPLADDR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUPLNAME {
            get {
                return this.SUPLNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.SUPLNAMEField, value) != true)) {
                    this.SUPLNAMEField = value;
                    this.RaisePropertyChanged("SUPLNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUPLNO {
            get {
                return this.SUPLNOField;
            }
            set {
                if ((object.ReferenceEquals(this.SUPLNOField, value) != true)) {
                    this.SUPLNOField = value;
                    this.RaisePropertyChanged("SUPLNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderMaster", Namespace="http://schemas.datacontract.org/2004/07/POPSWcfService.Entities")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrderMaster : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PODateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POPSMvcWcfApplication.ServiceReference1.PurchaseOrderDetails[] PODetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUPLNOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PODate {
            get {
                return this.PODateField;
            }
            set {
                if ((this.PODateField.Equals(value) != true)) {
                    this.PODateField = value;
                    this.RaisePropertyChanged("PODate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public POPSMvcWcfApplication.ServiceReference1.PurchaseOrderDetails[] PODetails {
            get {
                return this.PODetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.PODetailsField, value) != true)) {
                    this.PODetailsField = value;
                    this.RaisePropertyChanged("PODetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PONO {
            get {
                return this.PONOField;
            }
            set {
                if ((object.ReferenceEquals(this.PONOField, value) != true)) {
                    this.PONOField = value;
                    this.RaisePropertyChanged("PONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUPLNO {
            get {
                return this.SUPLNOField;
            }
            set {
                if ((object.ReferenceEquals(this.SUPLNOField, value) != true)) {
                    this.SUPLNOField = value;
                    this.RaisePropertyChanged("SUPLNO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderDetails", Namespace="http://schemas.datacontract.org/2004/07/POPSWcfService.Entities")]
    [System.SerializableAttribute()]
    public partial class PurchaseOrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITCode {
            get {
                return this.ITCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ITCodeField, value) != true)) {
                    this.ITCodeField = value;
                    this.RaisePropertyChanged("ITCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PONO {
            get {
                return this.PONOField;
            }
            set {
                if ((object.ReferenceEquals(this.PONOField, value) != true)) {
                    this.PONOField = value;
                    this.RaisePropertyChanged("PONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPopsService")]
    public interface IPopsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetItemById", ReplyAction="http://tempuri.org/IPopsService/GetItemByIdResponse")]
        POPSMvcWcfApplication.ServiceReference1.Item GetItemById(string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetItemById", ReplyAction="http://tempuri.org/IPopsService/GetItemByIdResponse")]
        System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.Item> GetItemByIdAsync(string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/AddItem", ReplyAction="http://tempuri.org/IPopsService/AddItemResponse")]
        void AddItem(POPSMvcWcfApplication.ServiceReference1.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/AddItem", ReplyAction="http://tempuri.org/IPopsService/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(POPSMvcWcfApplication.ServiceReference1.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetAllItems", ReplyAction="http://tempuri.org/IPopsService/GetAllItemsResponse")]
        POPSMvcWcfApplication.ServiceReference1.Item[] GetAllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetAllItems", ReplyAction="http://tempuri.org/IPopsService/GetAllItemsResponse")]
        System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.Item[]> GetAllItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/SaveItemDetails", ReplyAction="http://tempuri.org/IPopsService/SaveItemDetailsResponse")]
        void SaveItemDetails(POPSMvcWcfApplication.ServiceReference1.Item[] ItemsDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/SaveItemDetails", ReplyAction="http://tempuri.org/IPopsService/SaveItemDetailsResponse")]
        System.Threading.Tasks.Task SaveItemDetailsAsync(POPSMvcWcfApplication.ServiceReference1.Item[] ItemsDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetSupplierById", ReplyAction="http://tempuri.org/IPopsService/GetSupplierByIdResponse")]
        POPSMvcWcfApplication.ServiceReference1.Supplier GetSupplierById(string SNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetSupplierById", ReplyAction="http://tempuri.org/IPopsService/GetSupplierByIdResponse")]
        System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.Supplier> GetSupplierByIdAsync(string SNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/AddSuppier", ReplyAction="http://tempuri.org/IPopsService/AddSuppierResponse")]
        void AddSuppier(POPSMvcWcfApplication.ServiceReference1.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/AddSuppier", ReplyAction="http://tempuri.org/IPopsService/AddSuppierResponse")]
        System.Threading.Tasks.Task AddSuppierAsync(POPSMvcWcfApplication.ServiceReference1.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetAllSuppliers", ReplyAction="http://tempuri.org/IPopsService/GetAllSuppliersResponse")]
        POPSMvcWcfApplication.ServiceReference1.Supplier[] GetAllSuppliers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetAllSuppliers", ReplyAction="http://tempuri.org/IPopsService/GetAllSuppliersResponse")]
        System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.Supplier[]> GetAllSuppliersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/SaveSupplierDetails", ReplyAction="http://tempuri.org/IPopsService/SaveSupplierDetailsResponse")]
        void SaveSupplierDetails(POPSMvcWcfApplication.ServiceReference1.Supplier[] SupplierDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/SaveSupplierDetails", ReplyAction="http://tempuri.org/IPopsService/SaveSupplierDetailsResponse")]
        System.Threading.Tasks.Task SaveSupplierDetailsAsync(POPSMvcWcfApplication.ServiceReference1.Supplier[] SupplierDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetAllOrders", ReplyAction="http://tempuri.org/IPopsService/GetAllOrdersResponse")]
        POPSMvcWcfApplication.ServiceReference1.PurchaseOrderMaster[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetAllOrders", ReplyAction="http://tempuri.org/IPopsService/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.PurchaseOrderMaster[]> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetOrderDetails", ReplyAction="http://tempuri.org/IPopsService/GetOrderDetailsResponse")]
        POPSMvcWcfApplication.ServiceReference1.PurchaseOrderDetails[] GetOrderDetails(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/GetOrderDetails", ReplyAction="http://tempuri.org/IPopsService/GetOrderDetailsResponse")]
        System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.PurchaseOrderDetails[]> GetOrderDetailsAsync(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/AddOrder", ReplyAction="http://tempuri.org/IPopsService/AddOrderResponse")]
        void AddOrder(POPSMvcWcfApplication.ServiceReference1.PurchaseOrderMaster purchaseOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPopsService/AddOrder", ReplyAction="http://tempuri.org/IPopsService/AddOrderResponse")]
        System.Threading.Tasks.Task AddOrderAsync(POPSMvcWcfApplication.ServiceReference1.PurchaseOrderMaster purchaseOrder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPopsServiceChannel : POPSMvcWcfApplication.ServiceReference1.IPopsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PopsServiceClient : System.ServiceModel.ClientBase<POPSMvcWcfApplication.ServiceReference1.IPopsService>, POPSMvcWcfApplication.ServiceReference1.IPopsService {
        
        public PopsServiceClient() {
        }
        
        public PopsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PopsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PopsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PopsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public POPSMvcWcfApplication.ServiceReference1.Item GetItemById(string itemId) {
            return base.Channel.GetItemById(itemId);
        }
        
        public System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.Item> GetItemByIdAsync(string itemId) {
            return base.Channel.GetItemByIdAsync(itemId);
        }
        
        public void AddItem(POPSMvcWcfApplication.ServiceReference1.Item item) {
            base.Channel.AddItem(item);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(POPSMvcWcfApplication.ServiceReference1.Item item) {
            return base.Channel.AddItemAsync(item);
        }
        
        public POPSMvcWcfApplication.ServiceReference1.Item[] GetAllItems() {
            return base.Channel.GetAllItems();
        }
        
        public System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.Item[]> GetAllItemsAsync() {
            return base.Channel.GetAllItemsAsync();
        }
        
        public void SaveItemDetails(POPSMvcWcfApplication.ServiceReference1.Item[] ItemsDetails) {
            base.Channel.SaveItemDetails(ItemsDetails);
        }
        
        public System.Threading.Tasks.Task SaveItemDetailsAsync(POPSMvcWcfApplication.ServiceReference1.Item[] ItemsDetails) {
            return base.Channel.SaveItemDetailsAsync(ItemsDetails);
        }
        
        public POPSMvcWcfApplication.ServiceReference1.Supplier GetSupplierById(string SNo) {
            return base.Channel.GetSupplierById(SNo);
        }
        
        public System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.Supplier> GetSupplierByIdAsync(string SNo) {
            return base.Channel.GetSupplierByIdAsync(SNo);
        }
        
        public void AddSuppier(POPSMvcWcfApplication.ServiceReference1.Supplier supplier) {
            base.Channel.AddSuppier(supplier);
        }
        
        public System.Threading.Tasks.Task AddSuppierAsync(POPSMvcWcfApplication.ServiceReference1.Supplier supplier) {
            return base.Channel.AddSuppierAsync(supplier);
        }
        
        public POPSMvcWcfApplication.ServiceReference1.Supplier[] GetAllSuppliers() {
            return base.Channel.GetAllSuppliers();
        }
        
        public System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.Supplier[]> GetAllSuppliersAsync() {
            return base.Channel.GetAllSuppliersAsync();
        }
        
        public void SaveSupplierDetails(POPSMvcWcfApplication.ServiceReference1.Supplier[] SupplierDetails) {
            base.Channel.SaveSupplierDetails(SupplierDetails);
        }
        
        public System.Threading.Tasks.Task SaveSupplierDetailsAsync(POPSMvcWcfApplication.ServiceReference1.Supplier[] SupplierDetails) {
            return base.Channel.SaveSupplierDetailsAsync(SupplierDetails);
        }
        
        public POPSMvcWcfApplication.ServiceReference1.PurchaseOrderMaster[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.PurchaseOrderMaster[]> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public POPSMvcWcfApplication.ServiceReference1.PurchaseOrderDetails[] GetOrderDetails(string orderId) {
            return base.Channel.GetOrderDetails(orderId);
        }
        
        public System.Threading.Tasks.Task<POPSMvcWcfApplication.ServiceReference1.PurchaseOrderDetails[]> GetOrderDetailsAsync(string orderId) {
            return base.Channel.GetOrderDetailsAsync(orderId);
        }
        
        public void AddOrder(POPSMvcWcfApplication.ServiceReference1.PurchaseOrderMaster purchaseOrder) {
            base.Channel.AddOrder(purchaseOrder);
        }
        
        public System.Threading.Tasks.Task AddOrderAsync(POPSMvcWcfApplication.ServiceReference1.PurchaseOrderMaster purchaseOrder) {
            return base.Channel.AddOrderAsync(purchaseOrder);
        }
    }
}
